spring:
  #redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-wait:  5000
        max-idle:  8
        min-idle:  0
    timeout: 3000ms
    #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/iaw?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5  #空闲连接数
      idle-timeout: 180000 #连接存活时间
      maximum-pool-size: 10 #连接池最大连接数
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
      max-lifetime: 50000

#日志等级
logging:
  level:
    mapper: debug

#swagger文档开启/关闭
springfox:
  documentation:
    auto-startup: true